---
title: "HW1_zhengzhi"
author: "zhengzhi lin"
date: "2019.9.2"
output: pdf_document
---

P2

partA\
I want to get skills of a good swimmer and a burger eater out of this class.
List: tidy output, keras, burgers.

partB\
Three density funtions: 
                                pmf of poisson distribution: 
                               \[
 p(k)=\frac{\lambda^{k}e^{-\lambda}}{k!}\tag{1} \label{eq:special}
\]
                                pdf of normal standard distribution: \[
 f(x)=\frac{1}{\sqrt{2\pi}}e^{-\frac{x^2}{2}}\tag{2} \label{eq:special}
\]
                                pdf of uniform distribution: 
\[
 f(x)=
\begin{cases}
\frac{1}{a-b},& \text{for } a\leq x\leq b \\
0, & \text{otherwise}
\end{cases}\tag{3} \label{eq:special}
\]
\
P3\
About Rule 1, for every result, it might be hard to track espicially when a group of people is working together. Because everyone has its own style of programming, and they might not commit some result that they don't consider important or they could be lazy. Rule 2 might also create troubles for me because I am not familiar with UNIX, I will need a co-worker from CS department.
\
Issues I found when reading the article rules: 
\
Rule 1,
\
P4
```{r}
library(ggplot2)
data(diamonds)
plot(x=diamonds$carat,y=diamonds$depth,
     main = "scatter plot of diamonds carat&depth",
     ylab = "depth",xlab = "carat")
hist(x=diamonds$carat, xlab = "carat", 
     main = "histogram plot of diamonds carat", 
     ylim = c(0,20000))
```
Summary of problem 4: 

