---
title: "HW2_Lin"
author: "zhengzhi lin"
date: "2019.9.5"
output: pdf_document
---

##P3

For solo workers, version control helps them track every single step they made, and help them remember every decision they've made. 
For group workers, version control simply makes cooperating easier for each other, because by version control, they can know the progress on each one and the team can adjust to make things more efficient.

##P4
```{r}
library(dplyr)
url <- "https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/Sensory.dat"
operator <- read.table(url,fill = TRUE)
op_dat <- as.matrix(operator[-c(1:2),])
for (i in 1:10) {
  t <- op_dat[3*i-1,1:5]
  t <- c(i,t)
  op_dat[3*i-1,] <- t
  m <- op_dat[3*i,1:5]
  m <- c(i,m)
  op_dat[3*i,] <- m
  
}
op_dat <- as.data.frame(op_dat)
names(op_dat) <- c('item','operator1','operator2','operator3','operator4','operator5')
op_dat[,2:6] <- op_dat[,2:6] %>% mutate_if(is.factor, as.character)
op_dat[,2:6] <- op_dat[,2:6] %>% mutate_if(is.character, as.numeric)
head(op_dat) 
op_dat %>% str() %>% summary()



url <- "https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/LongJumpData.dat"
olympic <- read.table(url,fill = TRUE)
olympic <- as.matrix(olympic)
oly_dat <- rbind(olympic[-1,1:2],olympic[-1,3:4],olympic[-1,5:6],olympic[-1,7:8])
oly_dat <- as.data.frame(oly_dat)
names(oly_dat) <- c("year","Long Jump")
#oly_table <- oly_dat %>% summarize(mean=mean(`Long Jump`),var=var(`Long Jump`))
oly_dat <- oly_dat[-c(23,24),]
oly_dat <- oly_dat %>% mutate_if(is.factor,as.character) %>% mutate_if(is.character,as.numeric)
head(oly_dat)
oly_dat %>% str() %>% summary()

url <- 'https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/BrainandBodyWeight.dat'
weight <- read.table(url,fill = TRUE)
weight <- as.matrix(weight[-1,1:6])
weight_dat <- rbind(weight[,1:2],weight[,3:4],weight[,5:6])
weight_dat <- as.data.frame(weight_dat[-nrow(weight_dat),])
names(weight_dat) <- c("Body Wt","Brain Wt")
weight_dat <- weight_dat %>% mutate_if(is.factor,as.character) %>% mutate_if(is.character,as.numeric)
head(weight_dat)
weight_dat %>% str() %>% summary()


url <- 'https://www2.isye.gatech.edu/~jeffwu/wuhamadabook/data/tomato.dat'
tomato <- read.csv(url,sep = '\t')
tomato < - tomato %>% mutate_if(is.factor,as.character)
size <- paste(tomato[1,])
size <- strsplit(size," ")
size <- size[[1]][size[[1]]!=""]
size <- as.numeric(size[1:3])   
size <- as.vector(size)

ife <- paste(tomato[2,])
ife <- strsplit(ife,' ')
ife <- ife[[1]][ife[[1]]!=""]
ife[2:4] <- strsplit(ife[2:4],',')
name <- as.matrix(rep(ife[[1]],3))
ife <- rbind(ife[[2]],ife[[3]],ife[[4]])
ife <- ife %>% 
  cbind(name) %>% 
  cbind(c(1000,2000,3000))

pusa <- paste(tomato[3,])
pusa <- strsplit(pusa,' ')
pusa <- pusa[[1]][pusa[[1]]!=""]
pusa[2:4] <- strsplit(pusa[2:4],',')
name <- as.matrix(rep(pusa[[1]],3))
pusa <- rbind(pusa[[2]],pusa[[3]],pusa[[4]])
pusa <- pusa %>% 
  cbind(name) %>% 
  cbind(c(1000,2000,3000))
tomato_dat <- rbind(pusa,ife)
tomato_dat <- tomato_dat %>% as.data.frame()
colnames(tomato_dat) <- c('1st','2nd','3rd','name','plant density')
tomato_dat <- tomato_dat[,c("name","plant density",'1st','2nd','3rd')]

tomato_dat[,2:5] <- tomato_dat[,2:5] %>% 
  mutate_if(is.factor,as.character) %>% 
  mutate_if(is.character,as.numeric)

head(tomato_dat)
tomato_dat %>% str() %>% summary()

```


##P5
```{r}
library(dplyr)
plants <- read.csv('plants.csv')
plants <- plants %>% 
  select(Foliage_Color,pH_Min,pH_Max) %>% 
  na.omit() %>%
  mutate(
    pH_Mean=(pH_Min+pH_Max)/2
  ) %>%
  select(Foliage_Color,pH_Mean)

t <- lm(formula=pH_Mean~Foliage_Color,data=plants)
summary(t)
test <- aov(pH_Mean~Foliage_Color,data = plants)
summary(test)

```